language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
