language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script:
  - composer cs-check
  - composet test

after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer coveralls -v; fi
